Sq1 eliana/s07 listagem treinos estudante
DEVinHouse-Zucchetti/M3P-BackEnd pull request #20
Opened 2024-03-20 14:35 UTC by ElianaMT

Revisao backend finalizado

2024-03-23 01:40 UTC, CarolineSampaio requested changes
Boa noite, Eliana.

Fiz alguns comentários a respeito do código com sugestões de melhorias. Além deles, eu recomendária a implementação do conceito de service, repository e interface.

Fico à disposição para responder suas dúvidas e também para fazemos uma ligação para conversar e programar junto

2024-03-23 01:40 UTC, CarolineSampaio commented on app/Http/Controllers/WorkoutController.php
> +        try {
O bloco try catch pode ser removido, pois eu fiz uma configuração no projeto todo que já captura a exceção.

2024-03-23 01:40 UTC, CarolineSampaio commented on app/Http/Controllers/WorkoutController.php
> +            $workouts = Workout::select('workouts.*', 'students.name', 'exercises.description')
Apesa de estar funcionando, aqui podiamos usar códigos do laravel 10 ao invés da query pura.

Ficará assim:
  $workouts = Workout::with(['student', 'exercise'])
              ->where('student_id', $studentId)
              ->orderBy('created_at')
              ->get();

```php
$workouts = Workout::with(['student', 'exercise'])
                      ->where('student_id', $studentId)
                      ->orderBy('created_at')
                      ->get();
```
            
Bem menor né? Para que isso funcione precisamos fazer o relacionamento la no model. 

```php 
     public function student()
    {
        return $this->belongsTo(Student::class, 'student_id');
    }

    public function exercise()
    {
        return $this->belongsTo(Exercise::class, 'exercise_id');
    }
```

2024-03-23 01:40 UTC, CarolineSampaio commented on app/Http/Controllers/WorkoutController.php
> +                $day = $workout->day;
Esse workout->day poderia ser colocado diretamente:

```php
$formattingWorkouts['workouts'][$workout->day][] = [
....
```

2024-03-23 01:40 UTC, CarolineSampaio commented on app/Http/Controllers/WorkoutController.php
> +            return response()->json($formattingWorkouts);
O professor disponibilizou para nós uma traits a HttpResponses, que já está até importada no controller, bastaria alterar o returno para o seguinte código:

```php
 return $this->response('Listagem de treinos realizada com sucesso', Response::HTTP_OK, $formattingWorkouts);
```

Primeiro parâmetro -> mensagem, que poderia ser vazia também;
Segundo parâmetro -> status code;
Terceiro parâmetro-> array

2024-03-23 01:40 UTC, CarolineSampaio commented on routes/api.php
> +    Route::get('students/{id}/workouts', [WorkoutController::class, 'workoutsByStudent']);
Aqui na rota ficou faltando o ability para proteger a aplicação e garantir que apenas alunos possam ter acesso à essa rota.

```php
    Route::get('students/{id}/workouts', [WorkoutController::class, 'workoutsByStudent'])->middleware(['ability:get-workout']);
```

Já coloquei a ability correta

2024-03-23 01:40 UTC, CarolineSampaio commented on .env.example
> +DB_DATABASE=academiaf_api
Esse arquivo de configuração comum de todos, então não pode fazer essa alteração. Se fizer em seu computador, não poderá fazer o commit pois pode comprometer os colegas;

2024-03-30 23:51 UTC, ElianaMT commented
Refatora codigo usando nova tabela users_students

2024-03-30 23:54 UTC, ElianaMT commented
Os ajustes que você sugeriu @CarolineSampaio de try e catch farei ao final. :)

2024-03-31 19:08 UTC, ElianaMT commented
Adiciona testes no backend

2024-03-31 22:29 UTC, CarolineSampaio approved these changes
Testei o funcionamento e está ok, dentro do que você estipulou. Vou realizar a resolução dos conflitos e posterior merge.

2024-03-31 22:29 UTC, CarolineSampaio commented on tests/Unit/StudentWorkoutTest.php
> +    use DatabaseTransactions;
Linhas 11 a 58 podem ser removidas pois duplicam o que já existe nos últimos dois códigos.

O Data base transactions já foi aplicado globalmente também :D

2024-03-31 22:29 UTC, CarolineSampaio commented on tests/Unit/StudentWorkoutTest.php
> +        $response->assertStatus(200);
Além de dar um assert no status podemos colocar a estrutura esperada aqui:

```php
$response->assertStatus(200)->assertJsonStructure([
            'message',
            'status',
            'data' => [
                'student_id',
                'name',
                'workouts' => [
                    'SEGUNDA',
                    'TERÇA',
                    'QUARTA',
                    'QUINTA',
                    'SEXTA',
                    'SÁBADO',
                    'DOMINGO',
                ],
            ],
        ]);
```

2024-03-31 22:35 UTC, merged