Sq1 marcel/s01 login
DEVinHouse-Zucchetti/M3P-BackEnd pull request #6
Opened 2024-03-17 17:57 UTC by MarcelCNoronha

Neste pull request foi realizado:
-Definição dos metodos de login (Login e Logout) com criação dos perfis acesso e definição das autorizações dos respectivos perfis de acesso.
-Ajuste das rotas para respeitarem a autorização dos perfis de acesso. 
-Teste unitario das funções do authcontroller

2024-03-19 04:24 UTC, CarolineSampaio requested changes
Boa noite, fiz a revisão e teste da funcionalidade, fiz alguns comentários com ajustes que serão necessários. 
Qualquer dúvida fico a disposição para marcarmos um pair programming.

2024-03-19 04:24 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
>          try {
O bloco try catch deve ser removido uma vez que já foi tratado globalmente.

2024-03-19 04:24 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
>          try {
Recomendo que esse código seja transferido/tratado para um form request, retornando mensagens personalizadas em português:
```php
$request->validate([
    'email' => 'string|required',
    'password' => 'string|required'
]);
```

Usar como referência a implementação no projeto pets app->http->requests, além disso será necessário aplicar no método, conferir petController;

2024-03-19 04:24 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
> +            return $this->response('Autorizado', Response::HTTP_OK, [
Conferir ordem do formato do retorno, alterar para ficar como na imagem referência do documento do projeto.

2024-03-19 04:24 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
> +    private $permissions = [
As permissios ainda não estão funcionando pois faltou uma configuração no arquivo **kernel.php.**

Procure por  protected $middlewareAliases = [... 
Na última linha, após 'verified' => \Illuminate\Auth\Middleware\EnsureEmailIsVerified::class,

inserir essas duas linhas:
'abilities' => \Laravel\Sanctum\Http\Middleware\CheckAbilities::class,
'ability' => \Laravel\Sanctum\Http\Middleware\CheckForAnyAbility::class,

2024-03-19 04:24 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
>          try {
Acho que depois, seria interessante implementar o conceito de service e repository para deixar o código mais limpo.

Nesse primeiro momento, focar nas demais alterações relacionadas a permissão para que possamos disponibilizar para os colegas;

2024-03-19 22:18 UTC, MarcelCNoronha commented on app/Http/Controllers/AuthController.php
> +            return $this->response('Autorizado', Response::HTTP_OK, [
![image](https://github.com/DEVinHouse-Zucchetti/M3P-BackEnd/assets/95543728/75be0ed0-5e16-4615-b640-2ed55a3d6816)


No login está pedindo 200, que seria o Ok, mas estava com o 201 que e o created.

2024-03-19 22:19 UTC, MarcelCNoronha commented on app/Http/Controllers/AuthController.php
> +            return $this->response('Autorizado', Response::HTTP_OK, [
E padronizei o uso do responde::http
Como, manter ou deixar o 201?

2024-03-19 22:23 UTC, MarcelCNoronha commented on app/Http/Controllers/AuthController.php
>          try {
Ah sim. Está sendo tratado no Exceptions>Handler.php

2024-03-20 02:01 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
> +            return $this->response('Autorizado', Response::HTTP_OK, [
Como no documento, 200 ok. Já vi que ajustou :D

2024-03-20 23:29 UTC, CarolineSampaio approved these changes
Boa noite,, parabéns, tudo certinho :D

2024-03-20 23:29 UTC, CarolineSampaio commented on app/Http/Controllers/AuthController.php
>      public function logout(Request $request)
Alterar de:
$request->user()->currentAccessToken()->delete();

Para: 
$request->user()->tokens()->delete();

Ambos fazem o mesmo, vão pegar os tokens do usuário e deletar mas por algum motivo o primeiro está dando erro para verificar o token "atual" do user logado; A nova linha resolve o problema.

2024-03-20 23:29 UTC, CarolineSampaio commented on tests/Unit/UserTest.php
> +    public function test_login_and_logout()
Com a alteração da linha 94 do AuthController o logout está funcionando porém recomendaria utilizar a seguinte solução:

 public function test_admin_can_logout()
    {
        $user = User::factory()->create(['profile_id' => 1]);

        $response = $this->actingAs($user)->post('/api/logout');

        $response->assertStatus(Response::HTTP_NO_CONTENT);
    }
    
Primeiro criamos um user admin (profile_id=>1), em seguida agimos como um usuário logado (actingAs) e fazemos o post na rota do logout. Por fim verificamos o status 204.

2024-03-20 23:29 UTC, merged